version: "3.8"
services:
  react-app:
    #    stdin_open: true
    #    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - ./src:/app/src
#    environment:
#      - REACT_APP_NAME1=EvgeniyOm
#      - CHOKIDAR_USEPOLLING=true
#    env_file:
#      - ./.env